apiVersion: ENC[AES256_GCM,data:R2c=,iv:mAIiJdod0iOqGDEtIuyrY6Ze495vTgY4UFhpKTgbOCE=,tag:nrMLzqz26fS+cUKzMpIU6Q==,type:str]
data:
    password: ENC[AES256_GCM,data:XJyKPwoPF7j2ibM6,iv:nRG0dpdw+9OGZ4iKUSyo6X4bkd+zGfbf1vcSwDPU7xo=,tag:xSRFJOjZISktZR4cJh0KbA==,type:str]
    user: ENC[AES256_GCM,data:eujNfOnIaxo=,iv:UpWLkNoqHkF/3uVp9Yhjqj41/FLsbfiVjpzfgO1TOHU=,tag:QZ63Ov2nWN0qzJcIvp7hvw==,type:str]
kind: ENC[AES256_GCM,data:2OHx9dAp,iv:ma0Jh5KZYhQ2k4lk2Fsv59YcWjxk+px78Lrit1eM6ok=,tag:XbunTM0abNdhSQt0cZvKzg==,type:str]
metadata:
    creationTimestamp: null
    name: ENC[AES256_GCM,data:sjXCunI9CB8Q8Q==,iv:Ubp2s/C12erVD7upovLHtA4IJqKwPpEgPv2iyzbqsVc=,tag:EvXMsWgenk62eWj/Xlkaqw==,type:str]
    namespace: ENC[AES256_GCM,data:KOGlaMW9OA==,iv:Jtu0yvcrF6/Eeanlig6YoP1t6RssBd2aF8SzhiVib2c=,tag:G62xix1l8UjXRshVxAwLMg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-12-02T16:12:29Z"
    mac: ENC[AES256_GCM,data:nw04W0W0vKtOfY/gNxlQWBemvT0WDkysta2Mjvh6pNZftlCnarLE+63TVy895LcxQSYRyAj2yJsejdNq4K2027in1pALcXupuQpch5/GyBbi0xM0aCEs99CYzENxWCDn3Yb8SG6CfQQwDXUMRFveoQfbsQQHgOeIJIQ7cX5B0Ig=,iv:gAHtTCBqvbsGy6870Ix48AQNDLk7ZRRDMoWqlt1Gvuk=,tag:+fiRgK06WxK9sAzp8yq1ng==,type:str]
    pgp:
        - created_at: "2024-12-02T16:12:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAz0KYnRq77OHARAAiUeF7lVf57d/5SmgFgoLXdPa0krICxA49+5W/6/SLAcw
            +zGyA/ICA1UZPQj/F+r18D/67Md6V08IgxmeuhZImL6qGvDnz7cZN7tf5tkuMz5p
            IQrOivTM5Cx20liS90i6i5gPiga0X9Y9FXzOFjrcgMCmVh5hpJ8cri4KUJKCCm/i
            zTHH9PIV51apwD1XY2hVYV+9aE8cWPH1gPz/sBlROn7rYOqDesNzz6SppNjw3Iik
            McIl7yKBeEE8g09PBUT5ZRsVVviZyxx6tm3Z7H6uQtzjzoRwyhbGuN50NhVRnOTa
            F/8sT+McdRmBcCT+G0Toj/WUB3Jg2t7zmtVASljzIiflW/xurTErHGb/cO9PAYrN
            tHP3lsHvIAq72rQcSOPzOdu+g6mi4PNokZQbEnAjf4nBDwPs6p2yOxmDYsHvHyS/
            mDshTDw5BqrzvebEyX4F+Lq0UflK1Es7dXGUjqBV7uFY1+k5HocvMT0BMiIcJnpB
            iFUyLITNfyYM73hpP1mAIn33L8SmfFaDGe12Ruaab0iFQ/BjQ8qZ1IvrkHGxGqOi
            xVBDEOHOBkI0kVtAGZ0TP5hVLqS9Dsuio9LXS9IyXNzbeyyGaF0Pm1HnT3l2TMda
            j4ZNrdSYVvUbKPkxAcKA3pzEGSM/fjadwCocJZdU/KBajEkHlVRhtJTFWH2X2mTU
            aAEJAhDZapxlJcTfGMxvvbIXaI9cKkyNPk6YOLNEVBKrFjAyYVTExnNheHaXarLs
            zdZOK6FvBmQ3G2aMF8oydooB3Ko5IO0940FL+vdQWyxhtbldGXH+01NhIuWCPBHE
            3NhO9iff/RID
            =K+KZ
            -----END PGP MESSAGE-----
          fp: E9DE4D9149C0C2AD7D5A162DFC0ACB737FA25E42
    unencrypted_suffix: _unencrypted
    version: 3.9.1
